org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.daemon=false
org.gradle.configureondemand=false
android.useAndroidX=true
android.enableJetifier=false
android.suppressUnsupportedCompileSdk=34

# 网络代理（沙箱内通过本地代理访问外网）
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=18080
systemProp.http.nonProxyHosts=localhost|127.0.0.1|*.svc|*.cluster.local
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=18080
systemProp.https.nonProxyHosts=localhost|127.0.0.1|*.svc|*.cluster.local
